### ISSUE TITLE
zef can't install Inline::Perl5. Maybe Build.pm can't create the "resources" directory.

### ISSUE THREAD

**Issue by frithnanth** [niner/Inline-Perl5#100]
Hello,

the perl6 version I'm using is:

perl6 --version
This is Rakudo version 2017.08 built on MoarVM version 2017.08.1
implementing Perl 6.c.

When I try to install Inline::Perl5 I get this:

gretux:~# zef install Inline::Perl5
===> Searching for: Inline::Perl5
===> Building: Inline::Perl5:ver('0.29'):auth('github:niner')
===> Building [FAIL]: Inline::Perl5:ver('0.29'):auth('github:niner')
Aborting due to build failure: Inline::Perl5:ver('0.29'):auth('github:niner') (use --force-build to override)
  in code  at /opt/rakudo/share/perl6/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 331
  in method build at /opt/rakudo/share/perl6/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 296
  in sub  at /opt/rakudo/share/perl6/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 522
  in method install at /opt/rakudo/share/perl6/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 633
  in sub MAIN at /opt/rakudo/share/perl6/sources/31FF9E8498781BF95868DF98AD861FCF1211BCC1 (Zef::CLI) line 152
  in block <unit> at /opt/rakudo/share/perl6/resources/0031ECC6124802A80F7B7B073C50D0A1694E3020 line 1
  in sub MAIN at /opt/rakudo/bin/zef line 2
  in block <unit> at /opt/rakudo/bin/zef line 2

If I use the --force-build command parameter, zef spits a lot of lines like these:

===SORRY!=== Error while compiling /root/.zef/store/Inline-Perl5-0.29.tar.gz/Inline-Perl5-0.29/lib/Inline/Perl5/Interpreter.pm6 (Inline::Perl5::Interpreter)
An exception occurred while evaluating a constant
at /root/.zef/store/Inline-Perl5-0.29.tar.gz/Inline-Perl5-0.29/lib/Inline/Perl5/Interpreter.pm6 (Inline::Perl5::Interpreter):12
Exception details:
  ===SORRY!=== Error while compiling 
  Cannot locate native library '/root/.zef/store/Inline-Perl5-0.29.tar.gz/Inline-Perl5-0.29/resources/libraries/libp5helper.so': /root/.zef/store/Inline-Perl5-0.29.tar.gz/Inline-Perl5-0.29/resources/libraries/libp5helper.so: cannot open shared object file: No such file or directory
  at :

  in block <unit> at t/argv.t line 8

So, it looks like that Build.pm can't create the "resources" directory.

**Comment by niner** [comment]
I bet it's unable to compile p5helper.c. Do you have Perl 5's development headers installed?
You can probably get a better error message by running:
`git clone https://github.com/niner/Inline-Perl5.git && cd Inline-Perl5 && perl6 configure.pl6 && make`

**Comment by frithnanth** [comment]
You're right:

gcc -Wall p5helper.c -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ldl -lm -lpthread -lc -lcrypt -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/lib/x86_64-linux-gnu/perl/5.26/CORE  -shared -o "resources/libraries/libp5helper.so" -fPIC -g
/usr/bin/ld: cannot find -lperl

Yet, I have this file on my system:

/usr/lib/x86_64-linux-gnu/libperl.so.5.26.0

and if I hardcode it:

gcc -Wall p5helper.c -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -ldl -lm -lpthread -lc -lcrypt /usr/lib/x86_64-linux-gnu/libperl.so.5.26.0 -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/lib/x86_64-linux-gnu/perl/5.26/CORE  -shared -o "resources/libraries/libp5helper.so" -fPIC -g

the compilation is successful.
I guess it's some issue in the Debian (I'm using the sid distribution) perl package, which doesn't report all the directories it's using for its libraries.

**Comment by niner** [comment]
I think, there's some perl-dev package, you'd have to install.

**Comment by frithnanth** [comment]
Indeed there is, that solves the problem.
