### ISSUE TITLE
Inline::Perl5::Array.Capture is not same as Perl 6 Array.Capture

### ISSUE THREAD

**Issue by zoffixznet** [niner/Inline-Perl5#103]
`.Capture` return value is what drives behaviour behind signature unpacking, which can be quite useful:

```perl6
$ perl6 -e 'say [<a b c>].Capture; if [<a b c>] -> ($a, $b, $c) { dd [$a, $b, $c] }'
\("a", "b", "c")
["a", "b", "c"]
```

Inline::Perl5::Array.Capture's however, appears to use Mu.Capture that just dumps attributes, making the object a lot less useful:

```
\(:av(NativeCall::Types::Pointer.new(65479880)))
```

**Comment by niner** [comment]
Fixed in commit a41a62569a674c1ed77da7a55c55d75cead5a67c
Thanks for pointing this out!
