### ISSUE TITLE
`=finish` magic causes error about mapping code points

### ISSUE THREAD

**Issue by zoffixznet** [niner/Inline-Perl5#104]
I've used the `=finish` block in program to comment out a chunk I didn't need and noticed this error was generated, because I assume Inline::Perl5 treats `=finish` like `__DATA__`:

```
use Test::More:from<Perl5>;
=finish
Azərbaycan
```

Output:
```
Strings with code points over 0xFF may not be mapped into in-memory file handles
```

**Comment by niner** [comment]
Fixed in https://github.com/niner/Inline-Perl5/commit/9c573f9a0012653878d159cf5f7f2f565f2e077d
Thanks for the excellent report!
