### ISSUE TITLE
make test on OS X fails

### ISSUE THREAD

**Issue by kmnns** [niner/Inline-Perl5#11]
- OS X Yosemite
- Rakudo with MoarVM & Panda (no rakudobrew)
- Configured Perlbrew Perl 5.20.1 (as documented in the Inline::Perl5 README)

Installation via Panda fails due to failing tests, so I cloned and tried it myself:

```
perl6 configure.pl6
make all
```

This creates `lib/Inline/p5helper.dylib`.
Then:

```
make test
```

All tests fail with `unable to find Inline/p5helper.so IN @*INC`

**Edit**: I was able to work around this issue by renaming the `.dylib` to an `.so` file and then copying the `Inline` folder over to the Rakudo module directory `rakudo/install/languages/perl6/lib`

Still have some severe problems with most of the examples given in the README, but that might be a different issue.

**Comment by niner** [comment]
Commit 2fa40a1470d5bb0718bd5c0abfd5b4e1c546e238 should help you there.
Can you confirm? I don't have any OS X machine to test this.

**Comment by kmnns** [comment]
Yes, thanks. Nice fix.
