### ISSUE TITLE
Can NativeCall or IP5 take advantage of "When FFI Function Calls Beat Native C"?

### ISSUE THREAD

**Issue by raiph** [niner/Inline-Perl5#114]
This is quite possibly entirely the wrong place to post this but https://nullprogram.com/blog/2018/05/27/

Feel free to do whatever you wish with this and close this issue but I really wanted you to see it.

**Comment by lizmat** [comment]
AFAIK, nine already knows about it.

My takeaway is that yes, it can make a difference on null-load.  But as soon as you really start to do something in the routines you called, the difference disappears in the noise.
