### ISSUE TITLE
Intermittant error: Unsupported type NativeCall::Types::Pointer in p5_to_p6

### ISSUE THREAD

**Issue by 0racle** [niner/Inline-Perl5#121]
I'm using [`Net::OpenSSH`](https://metacpan.org/pod/Net::OpenSSH), which works fine... most of the time.

About 15% of the time, the script fails to parse with
```
Unsupported type NativeCall::Types::Pointer<102520880> in p5_to_p6
```
  > Pointer number differs each time.

The 15% figure comes from the following methodology.

```perl-6
# test.p6
use Net::OpenSSH:from<Perl5>;
```

```perl
# test.pl
use v5.26
use warnings;

my %ret;
for (1..100) {
    system(qw(perl6 test.p6));
    $ret{$?}++;
}
say "$_ : $ret{$_}" for keys %ret;
```

Output
```
0       : 85
256     : 15
```

I don't have this problem with other modules, so I presume it's something specific to something `Net::OpenSSH` is doing. If you're unable to replicate, let me know what I can do to capture more data for you.

Versions
```
% perl -v
This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-multi

% perl6 -v
This is Rakudo version 2018.06-438-g22f779a built on MoarVM version 2018.06-425-g0daf99b
implementing Perl 6.c.

% uname -a
Linux xxxxxxxx 2.6.32-696.13.2.el6.x86_64 #1 SMP Thu Oct 5 21:22:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

% cat /etc/centos-release
CentOS release 6.9 (Final)
```

**Comment by 0racle** [comment]
I'm not sure what version of Inline::Perl5 I was running. But I just did an upgrade (`sudo zef --force install Inline::Perl5`) and now it's happening 98% percent of the time.

**Comment by niner** [comment]
It's actually two bugs at play here. One causing Perl 5 package variables to be read during creation of the wrapper class and one that GLOB values are juts not supported in p5_to_p6. I've just pushed a fix for the former. Still need to add support for GLOBs, but this should get you up and running (the GLOB is in $Net::OpenSSH::debug_fh)

**Comment by niner** [comment]
GLOBs are now supprted with commit c5cf4dce6bf9d4deec1da10d49602ae2524ed746
