### ISSUE TITLE
Provide a way to hash-index objects

### ISSUE THREAD

**Issue by jnthn** [niner/Inline-Perl5#125]
There are [some modules](https://metacpan.org/pod/Spreadsheet::ParseExcel#Format) that provide object results, but do not provide methods to look into those objects, instead expecting one to use the hash interface. However, it seems there's no proper way to do this through `Inline::Perl5`. I came up with this horror:

    sub p5-obj-as-hash($obj) {
        my $wrapped = $obj.^attributes[0].get_value($obj);
        Inline::Perl5.^private_method_table<p5_hash_to_p6_hash>(Inline::Perl5.default_perl5, $wrapped)
    }

Which works, but that's totally breaking *two* kinds of encapsulation. Am I missing a good way, and if not, please can there be a good way?

**Comment by niner** [comment]
Implemented support for read access in commit cbe86102067e85139bb4400cd80a4357a435fcaf. Does this fix your issue?

**Comment by jnthn** [comment]
Yes, that seems to work very well, thanks. Only thing I notice: the commit adds to `t/lib/A.pm`, but then doesn't seem to add a test case?

**Comment by jnthn** [comment]
Also, it seems that the module is available on both the CPAN and GitHub ecosystems; do you know which one it'll install from? (So I know if I can rely on this feature with a normal dependency install, or have to wait for a "real" release.)

**Comment by niner** [comment]
Ah, classic case of starting a new file and forgetting to add it to the repo.
I can do a CPAN release in a couple of hours. It's about time to do that anyway.

**Comment by jnthn** [comment]
Great; thanks for the rapid response!
