### ISSUE TITLE
Cannot import Data::Printer

### ISSUE THREAD

**Issue by hhg7** [niner/Inline-Perl5#128]
I'm trying to import a Perl5 module I really like https://metacpan.org/pod/Data::Printer using advice from the manual page https://modules.perl6.org/dist/Inline::Perl5:cpan:NINE

using a very simple script

```
use Inline::Perl5;
my $p5 = Inline::Perl5.new;
$p5.use('Data::Printer');

```
but then I get this error:
```

Unsupported type NativeCall::Types::Pointer<94774650480224> in p5_to_p6
  in method p5_to_p6_type at /usr/lib/perl6/site/sources/130449F27E85303EEC9A19017246A5ED249F99E4 (Inline::Perl5) line 298
  in method unpack_return_values at /usr/lib/perl6/site/sources/130449F27E85303EEC9A19017246A5ED249F99E4 (Inline::Perl5) line 375
  in method invoke at /usr/lib/perl6/site/sources/130449F27E85303EEC9A19017246A5ED249F99E4 (Inline::Perl5) line 446
  in method import at /usr/lib/perl6/site/sources/130449F27E85303EEC9A19017246A5ED249F99E4 (Inline::Perl5) line 776
  in method use at /usr/lib/perl6/site/sources/130449F27E85303EEC9A19017246A5ED249F99E4 (Inline::Perl5) line 898
  in block <unit> at inline_perl5.p6 line 4

```
what is going wrong here? How can I import this perl5 module into perl6? I would also be happy if there is a similar way to get the colored/tabbed output in Perl6 like I would get from Data::Printer because I can't find it.

**Comment by niner** [comment]
This is fixed by commit c5cf4dce6bf9d4deec1da10d49602ae2524ed746
The problem came from Data::Printer's import sub which in the last statement assigned a sub to a type glob which caused the import to return that type glob which Inline::Perl5 hadn't been able to handle yet.
The commit adds support for passing Perl 5 type globs safely through Perl 6 code.

With this the following example (which is the recommended way) works just fine:
```
> perl6 -Ilib -e 'use Data::Printer:from<Perl5>; my @a = 1, 2, [3, 4, ${a => 1}]; p @a'
[
    [0] 1,
    [1] 2,
    [2] [
        [0] 3,
        [1] 4,
        [2] {
            a   1
        } (tied to Perl6::Hash)
    ]
]
```

**Comment by hhg7** [comment]
Thanks for your help, I appreciate it.  Isn't one of the main points of perl6 to provide simpler syntax over Perl5? This is much more complicated and user-unfriendly than Perl5.  Should the library be able to be loaded in the script and not at the command line? I never would have known this from reading the manual.

**Comment by niner** [comment]
You can put the `use Data::Printer:from<Perl5>;` in a script just fine. I just meant that this is better than ```
use Inline::Perl5;
my $p5 = Inline::Perl5.new;
$p5.use('Data::Printer');
```
My example was just the way I tested on the command line.
