### ISSUE TITLE
operation 'eq' not found

### ISSUE THREAD

**Issue by hhg7** [niner/Inline-Perl5#132]
I'm writing an excel xlsx spreadsheet with Perl6 and inline::Perl5.

When I write a line like

$file-location-ws.write($row, 2, $csv);

Perl6 crashes with the cryptic error message

    Operation "eq": no method found, left argument in overloaded package Perl6::Object, right argument has no overloaded magic at /usr/local/share/perl/5.26.0/Excel/Writer/XLSX/Worksheet.pm line 2020.

    in method invoke-parent at /home/con/.perl6/sources/130449F27E85303EEC9A19017246A5ED249F99E4 (Inline::Perl5) line 674 in sub many-args at /usr/lib/perl6/site/sources/D38010D24322CE1B1E6FFD8A463F23ED864152E9 (Inline::Perl5::ClassHOW) line 195 in block at 8.make_xlsx.p6 line 100

but if I replace $csv with a literal string of the filename 'Pumbaa Validation Plate 1 samplesheet.csv' thus

$file-location-ws.write($row, 2, 'Pumbaa Validation Plate 1 samplesheet.csv');

it works just fine. Obviously, this isn't a solution, since $csv will change.

Why is this error happening? How can I fix it?

I also have asked on SO https://stackoverflow.com/questions/54993385/perl6-crashes-left-argument-in-overloaded-package-perl6object

**Comment by hhg7** [comment]
I fixed this problem by assigning the variable to a `Str` type.  The problem was that I had no idea that this was a required type.  It would be great if type expectations like this could be fixed or introduced in future versions of Inline::Perl5.  The error message gave no hint of this.

**Comment by niner** [comment]
I think this is still an issue in Inline::Perl5.
The Perl6::Object wrapper class supports stringification: https://github.com/niner/Inline-Perl5/blob/master/lib/Inline/Perl5.pm6#L1135
For some reason though, Perl 5 seems to not fall back to stringification for non-overloaded eq op as it should. Will have to investigate.

**Comment by niner** [comment]
Perl 5 needs an overloaded 'cmp' to auto generate the stringy comparison operators. The alternative would have been an explicit fallback => 1, but then you'd only compare the "Perl6::Object=HASH(0x12345678)" which is arguably much less useful.
