### ISSUE TITLE
`use Data::Printer:from<Perl5> {show_tied => 0}` doesn't switch `show_tied` off 

### ISSUE THREAD

**Issue by raiph** [niner/Inline-Perl5#135]
Hi @niner,

I'm posting this on behalf of the user (@hhg7 here on GH; @con on SO) who posted [SO "Altering parameters in Data::Printer in Perl6"](https://stackoverflow.com/questions/55799219/altering-parameters-in-dataprinter-in-perl6).

Aiui, `use Data::Printer {show_tied => 0}` turns `show_tied` off in P5 but `use Data::Printer:from<Perl5> {show_tied => 0}` fails to do so in P6.

I could well believe that you consider progressing problems such as this as being out of scope for this issues queue. But perhaps not. Either way, any commentary, advice, etc. would be welcome.

**Comment by niner** [comment]
The solution is rather simple: `use Data::Printer:from<Perl5> 'show_tied', 0;`
The fat comma `=>` is a Pair constructor in Perl 6/Raku while it's really just a fancy comma in Perl 5. Raku considers Pair arguments to be used for importing tags like `:ALL` (which is equivalent to `ALL => True`). To get around this and pass what Perl 5 code expects, just list the values individually.
@raiph can you please post this to SO, too for completeness?

**Comment by raiph** [comment]
Awesome. Thanks. Posted.

**Comment by raiph** [comment]
Now turned into [a cleaned up and elaborated Q+A](https://stackoverflow.com/questions/59556587/how-do-i-turn-the-perl-5-module-dataprinters-show-tied-option-off-when-usin).
