### ISSUE TITLE
Inline::Perl5 doesn't appear to play well with plenv, fails to install

### ISSUE THREAD

**Issue by ravenhall** [niner/Inline-Perl5#138]
nwaddell@Beleriand ~ $ plenv --version
plenv 2.3.0-6-gac7a13b
nwaddell@Beleriand ~ $ perl6 --version
This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1
implementing Perl 6.d.
nwaddell@Beleriand ~ $ zef --version
v0.8.0
nwaddell@Beleriand ~ $ which perl
/home/nwaddell/.plenv/versions/5.30.0/bin/perl
nwaddell@Beleriand ~ $ plenv global
5.30.0
nwaddell@Beleriand ~ $ perl -v

This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2019, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

nwaddell@Beleriand ~ $ zef install Inline::Perl5
===> Searching for: Inline::Perl5
===> Building: Inline::Perl5:ver<0.42>:auth<github:niner>
[Inline::Perl5] /usr/bin/ld: /home/nwaddell/.plenv/versions/5.30.0/lib/perl5/5.30.0/x86_64-linux/CORE/libperl.a(op.o): relocation R_X86_64_PC32 against symbol `PL_compcv' can not be used when making a shared object; recompile with -fPIC
[Inline::Perl5] /usr/bin/ld: final link failed: Bad value
[Inline::Perl5] collect2: error: ld returned 1 exit status
[Inline::Perl5] make: *** [/home/nwaddell/.zef/store/Inline-Perl5-0.42.tar.gz/Inline-Perl5-0.42/resources/libraries/libp5helper.so] Error 1
[Inline::Perl5] The spawned command 'make' exited unsuccessfully (exit code: 2)
[Inline::Perl5]   in method build at /home/nwaddell/.zef/store/Inline-Perl5-0.42.tar.gz/Inline-Perl5-0.42/Build.pm line 21
[Inline::Perl5]   in block <unit> at -e line 1
===> Building [FAIL]: Inline::Perl5:ver<0.42>:auth<github:niner>
Aborting due to build failure: Inline::Perl5:ver<0.42>:auth<github:niner> (use --force-build to override)

**Comment by niner** [comment]
Please have a look at the README. It contains instructions on how to install with plenv.
