### ISSUE TITLE
Inline::Perl5 fails tests on Ubuntu

### ISSUE THREAD

**Issue by tbrowder** [niner/Inline-Perl5#146]
Using @tony-o's nightly Docker the build of Inline::Perl5 shows a compiler warning that apparently causes testing failure.

I discovered the failure when using Travis to test my Raku module Excel. @melezhik showed the failure on rakudist for Ubuntu but success on Debian.

**Comment by melezhik** [comment]
Corrections ( sorry if I was not clear on IRC ):

on ubuntu test succeed:

http://repo.westus.cloudapp.azure.com/rakudist/reports/Excel/ubuntu/1588279548.txt

**Comment by melezhik** [comment]
on debian test succeeds as well:

http://repo.westus.cloudapp.azure.com/rakudist/reports/Excel/debian/1588281493.txt

**Comment by tbrowder** [comment]
Ah, sorry, it must be @tony-o's Docker container somehow. But I did file an issue there also.
