### ISSUE TITLE
Apparently this can't be installed using zef

### ISSUE THREAD

**Issue by JJ** [niner/Inline-Perl5#154]
Maybe mention that in the README?

```
➜  Chapter-15 git:(master) ✗ zef install Inline::Perl5
===> Searching for: Inline::Perl5
===> Searching for missing dependencies: perl:from<native>, Distribution::Builder::MakeFromJSON:ver<0.6+>
===> Failed to find dependencies: perl:from<native>
Failed to resolve some missing dependencies
```

Perl has been installed according to instructions.

**Comment by rakulius** [comment]
I also have the same issue.

**Comment by zerodogg** [comment]
It does work just fine installing from zef, but it needs the perl development headers to be present. For instance, on Debian it needs libperl-dev

**Comment by JJ** [comment]
> It does work just fine installing from zef, but it needs the perl development headers to be present. For instance, on Debian it needs libperl-dev

Which is precisely what was said in the original post, add to README some instructions on how to install prerequisites and which ones are needed

**Comment by zerodogg** [comment]
It already says that in the README - https://github.com/niner/Inline-Perl5#building

**Comment by tbrowder** [comment]
But to be fair it could be made a bit more obvious. Emphasizing and naming the exact package name for major distros would help.

**Comment by zerodogg** [comment]
You're not wrong. Maybe we could compile a table of perl-dev packages? And there could be a note in DESCRIPTION along the lines of "Note that this module requires the perl development libraries in order to build. See the building section below for more information"?
