### ISSUE TITLE
macOS Searching for missing dependencies: perl:from<native>

### ISSUE THREAD

**Issue by p6steve** [niner/Inline-Perl5#171]
Hi

I am getting this:

% zef --verbose install https://github.com/niner/Inline-Perl5.git
===> Fetching [OK]: https://github.com/niner/Inline-Perl5.git to /Users/stephenroe/.zef/tmp/1634205719.48882.4889.5786039593695/Inline-Perl5.git
===> Extraction [OK]: https://github.com/niner/Inline-Perl5.git to /Users/stephenroe/.zef/store/Inline-Perl5.git
===> Searching for missing dependencies: perl:from<native>
No such method 'as' for invocant of type 'Any'

I am on:

Welcome to Rakudo(tm) v2021.04.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.04.

and:
macOS Big Sur 11.6

please can you help?

**Comment by sdondley** [comment]
ditto, running 2021.12 installed from binary on macos monterey.

**Comment by p6steve** [comment]
hi @sdondley  - I didn't wait for this to be resolved, but for many reasons, decided to move to vftools/docker on macOS Monterey M1 ... I have posted a 2 part howto here http://p6steve.com

sorry not to have been more helpful...

**Comment by seaker** [comment]
May be your local perl package missed the following flag when compiling: -Duseshrplib

**Comment by sdondley** [comment]
@seaker Yeah, I saw that option mentioned in the README. I tried it but unfortunately perl is not compiling and I'm getting test faiulres using perlbrew. Haven't had a chance to look into why yet. Frustrating.

**Comment by p6steve** [comment]
Hi @sdondley - I have found a couple of minutes to try my had on this...

## ```zef install Inline::Perl5```
===> Failed to find dependencies: perl:from<native>
Failed to resolve some missing dependencies (use e.g. --exclude="perl" to skip)

## so ```zef install Inline::Perl5 --exclude="perl"``` (just following orders)
... taking a LONG time

## so ```zef install File::Temp --verbose``` install the deps one by one

## and ```zef install -v Distribution::Builder::MakeFromJSON:ver<0.6+>```
zsh: parse error near `\n' [no like angle brackets in zsh]

## so ```zef install -v Distribution::Builder::MakeFromJSON```
got ver<0.16>
## then ```zef install -v System::Query```
... taking a LONG time

hmmm - running out of patience to hand install this stuff ... 
... I am getting the feeling that even if the rakudo binary makes it OK, expecting to chuck in a casual Inline::Perl5 install on macOS Monterey M1 is still not practical




Error:

**Comment by niner** [comment]
I've just uploaded Inline::Perl5 0.58 which no longer carries the uncheckable dependency on libperl.so (since this library gets installed into a non-standard location and installers like zef can't really check for it). No other changes.

Unfortunately I'm no help with the library loading problem on MacOS. I do not have any Apple systems and the error message does not tell anything useful.

**Comment by sdondley** [comment]
OK, after overcoming my own stupidity and getting perl 5.34 installed on my mac on an intel machine using the -Dusehrplib switch, Inline::Perl5 successfully installed. Woot!

On my m1, I'm now getting a huge, huge dump of errors. I may have been trying to install on the wrong version of perl earlier. Anyway, one of the errors is `ld: symbol(s) not found for architecture x86_64`

This leads be to believe it's just not possible on an m1 at this point.

**Comment by sdondley** [comment]
And here's the almost 6000 lines of error code I get when trying to install on my M1: https://pastebin.com/DEZTGGgV

**Comment by p6steve** [comment]
@sdondley - I am totally not surprised by your macOS M1 Monterey errors - I don't know if you have read my recent blog [posts](https://p6steve.com), but this is pretty much the conclusion I drew. I suspect that M1 is a tough nut for the package installer world for all languages and I can see that something deep is broken in rakudo/zef (threading?). 

If, like me, you have just paid $$$ and cannot/will not go back to x86, then there are two paths that have worked well for me (which both rely on ubuntu and apt-get ability to handle architecture dependencies):
- Docker Desktop ... convenient and user friendly ... happily runs arm64 and/or amd64 images (under rosetta)
- vftools ... pure native arm64 on cli only ... 

suggest we close this issue for now until the rakudo builders have done their magic on M1

**Comment by sdondley** [comment]
Right, the original issue has been solved with 0.58. The m1 issue is totally separate. Fortunately, I don't use the m1 much for development and I'll have my intel imac around for at least a couple of more years.

**Comment by niner** [comment]
Does this mean anything to you? https://discussions.apple.com/thread/3914962

**Comment by sdondley** [comment]
No, but I'm wondering if installing xcode on my m1 might supply the necessary libraries. I'll give it a shot.

**Comment by lizmat** [comment]
FWIW, I've always had to install XCode on my Mac to get any compilation going.

**Comment by sdondley** [comment]
Installing xcode didn't help.

**Comment by sdondley** [comment]
Oh, wow, got it working on the M1 by switching off perlbrew and using the system perl. So what does that tell us?

**Comment by sdondley** [comment]
I'm going to try installing perl with perlbrrew and xcode intalled. I'm gonna guess the problem was my version of perlbrew was not installed when I had xcode installed.

**Comment by sdondley** [comment]
OK! Inline `Perl5::Inline` has been successfully installed against system perl and with perl installed with perlbrew with Xcode. I think we are good!
