### ISSUE TITLE
Module pretends it built correctly when it did not

### ISSUE THREAD

**Issue by tadzik** [niner/Inline-Perl5#20]
Not sure if it's LibraryMake's problem, but here's where I encountered it: https://gist.github.com/tadzik/390b6c6ecbc9ac39f6d3

p5helper.so didn't build, but Build.pm doesn't fail, so panda continues as if it worked fine.

**Comment by niner** [comment]
A couple of bug reports about installation failures show that this works as intended nowadays. Closing.
