### ISSUE TITLE
Doesn't build even with -fPIC compiled Perl

### ISSUE THREAD

**Issue by tadzik** [niner/Inline-Perl5#21]
https://gist.github.com/tadzik/c5d7694d5c0c74047324

It says to recompile Perl with -fPIC, even though Perl is (claims to be?) compiled with -fPIC.

Is it a bug, or am I missing something?

**Comment by niner** [comment]
You seem to be linking against libperl.a instead of libperl.so. How did you compile perl?
For plenv, I _guess_ the correct way would be:
    plenv install 5.20.2 -Duseshrplib

**Comment by tadzik** [comment]
On 09/05/15 18:38, niner wrote:
> plenv install 5.20.2 -Duseshrplib

Yeah, you were correct; I was using -Dcccdlflags=-fPIC. Thanks, now it 
works fine.
