### ISSUE TITLE
Missing P5import.pm

### ISSUE THREAD

**Issue by quester** [niner/Inline-Perl5#24]
In t/from.t, at line 11, commit 41bda401eb715114240d09a5b88e4e43007531f4:

use P5Import:from<Perl5> <tests 2>;

I don't have P5import.pm and didn't see it in Google.  This causes the test to fail:

===SORRY!===
Can't locate P5Import.pm in @INC (you may need to install the P5Import module) (@INC contains: t/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at (eval 1) line 66.
BEGIN failed--compilation aborted.
t/from.t ...................... 
No subtests run 

Thank you very much,
- quester

**Comment by niner** [comment]
Seems like I forgot to add them. Fixed in commit 7e03fc9eaf12d730cb3f7ed67a4ba792b62bc554
Sorry for the inconvenience and thanks for reporting!
