### ISSUE TITLE
Need to check for presence of Filter::Simple

### ISSUE THREAD

**Issue by quester** [niner/Inline-Perl5#25]
The CPAN module Filter::Simple is a prerequisite for Inline::Perl5; it's used in lib/Inline/Perl5.pm6.

Although Filter::Simple is a core module it is not unlikely that perl5 will be installed without it, even if the perl5 version is very recent.  The packaging of Linux distributions can be a wondrous thing...

The Red Hat Enterprise/CentOS/Fedora, OpenSuSE, Mandriva, PCLinuxOS, and Mageia distributions of Linux all have a separate package named perl-Filter-Simple that will need to be installed separately (x perl-Filter-Simple, where x is yum install, dnf install,  apt-get install, zypper in, or yast -i depending on the system)  For the RedHat/Centos/Fedora family only, it can be installed as part of a package called perl-core, which includes all of the core modules.

For Debian/Ubuntu, perl-base (a minimal install) does not include Filter::Simple.  The full install of perl, which is a package just named "perl", has perl-modules as a prerequisite and that does include Filter::Simple.

I would suppose that the installation scripts should just stop and tell the user that the module needs to be installed if it's missing and let the user decide which installer they would like to use, rather than worrying about  distribution details.

Thank you very much for all your hard work!
- quester

**Comment by niner** [comment]
Implemented in commit a1c1d93
Thanks for the suggestion!

FWIW on my openSUSE installation, Filter::Simple is part of the perl package:
~> rpm -qf /usr/lib/perl5/5.20.1/Filter/Simple.pm
perl-5.20.1-3.1.x86_64
