### ISSUE TITLE
Inconsistency between use :from<Perl5> and EVAL :lang<perl5>

### ISSUE THREAD

**Issue by hoelzro** [niner/Inline-Perl5#28]
`use Module:from<Perl5>` uses uppercase `Perl5`, while `EVAL "source code", :lang<perl5>` uses lowercase `perl5`.  Is there a way they could be made consistent, or both cases could work?

**Comment by niner** [comment]
I changed rakudo and the spec to use "Perl5" in both cases.
Thanks for reporting this!
