### ISSUE TITLE
t/callables.t occasionally panics with "panic: MUTEX_LOCK (22)"

### ISSUE THREAD

**Issue by hoelzro** [niner/Inline-Perl5#34]
This is a crazy issue, so grab a drink and maybe something to eat.

# Short Fix

Remove `my &callable := $p5.call('return_code', 'Foo');` from `t/callables.t`

# Long Fix

Before I get into the long but "proper" fix, a bit of background:

I'm not able to reproduce this issue for every Rakudo/Inline::Perl5 combination; one I can get to reliably fail is this:

    $ perl6 --version
    This is perl6 version 2015.06-275-g48c0ba5 built on MoarVM version 2015.06-98-gf22142b
    $ cd Inline-Perl5 && git show
    commit e314d53
    Author: Stefan Seifert <nine@detonation.org>
    Date:   Wed Jul 8 18:02:04 2015 +0200
    
        Fix loading P5 modules from P6 code run by Inline::Perl6
     
        Add missing XS hookup when Inline::Perl5 is loaded by Inline::Perl6
        Fixes: $p6.run('use Foo:from<Perl5>;');
    
    diff --git a/p5helper.c b/p5helper.c
    index 495d1a6..512f97c 100644
    --- a/p5helper.c
    +++ b/p5helper.c
    @@ -23,6 +23,7 @@ void p5_inline_perl6_xs_init(PerlInterpreter *my_perl) {
         char *file = __FILE__;
         newXS("Perl6::Object::call_method", p5_call_p6_method, file);
         newXS("Perl6::Callable::call", p5_call_p6_callable, file);
    +    newXS("v6::load_module_impl", p5_load_module, file);
     }
     
     static int inited = 0;

I have only seen this happen when the tests are run via `panda-test`; never via `prove` on its own.

The issue seems to be that the `Inline::Perl5` `DESTROY` submethod tears down the Perl 5 interpreter and then the `DESTROY` submethod on a `Perl5Callable` is invoked.  The global data structures that `perl` uses (such as its op mutex) have been taken down and are not in a usable state, so `pthread_mutex_lock` sees the misconfigured mutex and freaks out, returning `EINVAL` (which is the 22 we see)

So a change needs to happen so that `Perl5Callable` objects are never collected after their `Inline::Perl5` ones; this is probably a Rakudo or MoarVM change.

Here's a dumb script I wrote to test the presence of the bug:

```bash
#!/bin/bash

good_count=0
bad_count=0

for i in $(seq 1 100); do
    if panda-test >/dev/null 2>&1  ; then
        good_count=$(( $good_count + 1 ))
    else
        bad_count=$(( $bad_count + 1 ))
    fi
done

echo "# good: $good_count"
echo "# bad:  $bad_count"
```

**Comment by niner** [comment]
hoelzro you are my hero! This has first been reported in October 2014, when Inline::Perl5 was barely over a month old, but I've never managed to reproduce it reliably, even when setting up a VM with the same environment as the reporter. Your diagnosis makes perfect sense.

I'm not sure how far we will get trying to convince people, that rakudo needs to obey some order when calling DESTROY. As a fix, I can have p5_destruct_perl set a "destroyed" flag that p5_sv_refcnt_dec checks. This is kind of a hot path, but doing this in C, I guess it will still not have measurable performance impact. At least until we get proper performance out of NativeCall.

**Comment by niner** [comment]
Hopefully fixed in commit a61cdc6271d244c8762e04d4855992288930f70f
Can you still reproduce it with this patch?

**Comment by hoelzro** [comment]
@niner The good news is that I can *not* reproduce on a61cdc6!  The bad news is that I can't on its parent 2cab928 either, and applying the patch on top of e314d53 (the revision I can consistenly get to fail) *does* reproduce the behavior.

I do think, however, that Rakudo needs to have some order to `DESTROY` we programmers can rely on.  I doubt this the first time something like this will come up.

**Comment by hoelzro** [comment]
Further fun with this issue:

  - Adding `use nqp` to t/callables.t "fixes" the problem
  - Substituting `withp6lib` in `Panda::Tester` with an equivalent setting to `%ENV<PERL6LIB>` doesn't reproduce the issue

**Comment by hoelzro** [comment]
Ok, I was mistaken in my thoughts on `DESTROY` order, but `DESTROY` *does* play a role in this bug.  The real culprit is the `END` block at the end of `Inline::Perl5`: https://github.com/niner/Inline-Perl5/blob/b4318ced4f51b04617e78d986b405daedd5ef074/lib/Inline/Perl5.pm6#L852

`p5_terminate` tears down all of the global things that `perl` uses, and after the `END` block is run is when the `DESTROY` methods are run.  That's the bug!

I don't know what the proper way to proceed with this is; perhaps tie `p5_terminate` to the last `DESTROY` called on an `Inline::Perl5` object?  I think since the process is exiting, it's probably ok to omit `p5_terminate` for the time being.

**Comment by niner** [comment]
Ok, a new try in commit b561782e58448853355f2855f79a1427733f2761
p5_terminate now only sets a flag that p5_destruct_perl checks to see if in addition to perl_destruct() and perl_free() it should also PERL_SYS_TERM()
Can you please re-test?

**Comment by hoelzro** [comment]
@niner I ran my test script on a recent Rakudo and Inline::Perl5 and didn't see the issue; I think it's probably safe to close this issue!
