### ISSUE TITLE
'panda install' error under Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by drforr** [niner/Inline-Perl5#36]
==> Fetching Inline::Perl5
==> Building Inline::Perl5
gcc -Wall p5helper.c `perl -MExtUtils::Embed -e ccopts -e ldopts` -shared -o /home/jgoff/External-Repositories/Inline-Perl5/.panda-work/1438262714_1/blib/lib/Inline/p5helper.so -fPIC -g
/usr/bin/ld: /home/jgoff/perl5/perlbrew/perls/perl-5.20.2/lib/5.20.2/x86_64-linux/CORE/libperl.a(op.o): relocation R_X86_64_32S against `PL_sv_yes' can not be used when making a shared object; recompile with -fPIC
/home/jgoff/perl5/perlbrew/perls/perl-5.20.2/lib/5.20.2/x86_64-linux/CORE/libperl.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [/home/jgoff/External-Repositories/Inline-Perl5/.panda-work/1438262714_1/blib/lib/Inline/p5helper.so] Error 1
make exited with signal 2
  in sub die at /home/jgoff/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm:1
  in sub make at lib/LibraryMake.pm6:203
  in method build at /home/jgoff/External-Repositories/Inline-Perl5/.panda-work/1438262714_1/Build.pm:19
  in block  at lib/Panda/Builder.pm:78
  in method build at lib/Panda/Builder.pm:73
  in method install at lib/Panda.pm:127
  in method resolve at lib/Panda.pm:218
  in sub MAIN at /home/jgoff/.rakudobrew/moar-nom/install/share/perl6/site/bin/panda:20
  in block <unit> at /home/jgoff/.rakudobrew/moar-nom/install/share/perl6/site/bin/panda:87

**Comment by niner** [comment]
As documented in the README, you have to supply the -Duseshrplib flag to perlbrew when compiling perl to make it usable with Inline::Perl5.

**Comment by drforr** [comment]
Ah, that's the problem with having everything under perlbrew, embarrassed I didn't catch the 'recompile with -fPIC' bit.
