### ISSUE TITLE
Add syntactic sugar

### ISSUE THREAD

**Issue by ghost** [niner/Inline-Perl5#4]
Making `Inline::Perl5` into a `Callable` backed by a multi-method yields some nice sugar:

    my &p5 = Inline::Perl5.new;

    # run code
    p5 'print "hello world\n"';
    p5 q{{{
        use DBI;
        DBI->connect('dbi:Pg:database=timemngt');
    }}};

    # call sub
    p5 :print('hello world\n');

    # call method
    p5 'DBI', :connect<dbi:Pg:database=timemngt>;

    # call methods on the interpreter
    p5.DESTROY;

The code implementing this:

    method invoke($_) { $.dispatch(|.list, |.hash.pairs) }
    multi method dispatch(Str $code) { $.run($code) }
    multi method dispatch(Pair (:$key, :$value)) { $.call($key, |$value) }
    multi method dispatch($obj, Pair (:$key, :$value)) { $.send($obj, $key, |$value) }
    multi method dispatch() { self }

Note that instead of `invoke`, `send` needs to be used for method calls as the former is used by Rakudo internally.

There are a few things you'd have to keep in mind:

    # passing a single array argument flattens
    p5 :foo([1, 2, 3]);

    # avoid flattening by using a trailing comma
    p5 :foo([1, 2, 3],);

**Comment by niner** [comment]
We nowadays have:
#!perl6
use DBI:from<Perl5>;
my $dbh = DBI.connect(...);

I think it doesn't get any sweeter than that :) Though if there are suggestions, I'd certainly be interested.
Is there a concensus that we can close this issue?

**Comment by niner** [comment]
As a uni professor of mine used to say: silence is acceptance. With use :from<Perl5> and EVAL :lang<Perl5> I think we have all the sugar we can get.
