### ISSUE TITLE
Detect and handle Perl without multiplicity

### ISSUE THREAD

**Issue by hoelzro** [niner/Inline-Perl5#43]
@kanatohodets pointed this out to me at the SPW, and I'm just now getting a round to filing this as an issue =/

Basically, the issue is that a user can use `Inline::Perl5` on a perl without multiplicity, which isn't a problem until they try to create a second Perl5Interpreter object.  I think that checking the `MULTIPLICITY` or `PERL_IMPLICIT_CONTEXT` macros and throwing an error on the second construction attempt would probably be a good way to handle this.

**Comment by niner** [comment]
Fixed in commit 81243ea6518267be718bf5e092e9c09b9a36f281.
We now throw a X::Inline::Perl5::NoMultiplicity in that case.
