### ISSUE TITLE
Problem Installing on Windows 10

### ISSUE THREAD

**Issue by Odud** [niner/Inline-Perl5#48]
_I've hit an issue when installing using panda on W10, I assumed that this was the right way to install it. I don't know enough about gcc to take it further myself. Here's what happens::_

PS C:\Users\langb\dropbox\perl6> panda install Inline::Perl5
==> Fetching Inline::Perl5
==> Building Inline::Perl5

Microsoft (R) Program Maintenance Utility Version 14.00.23026.0
Copyright (C) Microsoft Corporation.  All rights reserved.

rm C:\Users\langb\dropbox\perl6.panda-work\1446633495_1/blib/lib/Inline/p5helper.dll
Could Not Find C:\Users\langb\dropbox\perl6.panda-work\1446633495_1\blib\lib\Inline\p5helper.dll
gcc -Wall p5helper.c `perl -MExtUtils::Embed -e ccopts -e ldopts` -shared -o C:\Users\langb\dropbox\perl6.panda-work\1446633495_1/blib/lib/Inline/p5helper.dll -fPIC -g
gcc.EXE: error: `perl: No such file or directory
gcc.EXE: error: unrecognized command line option '-MExtUtils::Embed'
NMAKE : fatal error U1077: 'C:\Strawberry\c\bin\gcc.EXE' : return code '0x1'
Stop.
make exited with signal 2
  in sub make at C:\rakudo\share\perl6\site\lib\LibraryMake.pm6:185
  in method build at C:\Users\langb\dropbox\perl6.panda-work\1446633495_1\Build.pm:19
  in block  at C:\rakudo/share/perl6/lib/Panda/Builder.pm:13
  in method build at C:\rakudo/share/perl6/lib/Panda/Builder.pm:8
  in method install at C:\rakudo/share/perl6/lib/Panda.pm:133
  in method resolve at C:\rakudo/share/perl6/lib/Panda.pm:219
  in sub MAIN at C:\rakudo\bin\panda:18
  in block <unit> at C:\rakudo\bin\panda:95

PS C:\Users\langb\dropbox\perl6>

**Comment by Odud** [comment]
The perl -MExtUtils bit is surrounded by backticks, I think I fell over the Markdown syntax...

**Comment by niner** [comment]
Seems like it's not only Markdown but also nmake that doesn't cope too well with those backticks. Unfortunately my last Windows development experience was more than 15 years ago, so I have no idea how to deal with such issues :/

**Comment by FROGGS** [comment]
Can someone point to the actual code that contains these backticks?

**Comment by niner** [comment]
https://github.com/niner/Inline-Perl5/blob/master/Makefile.in#L6

If nmake doesn't support backticks at all, I may have to run the command in Build.pm and configure.pl6 and pass it on as a variable to LibraryMake for generating the Makefile

**Comment by FROGGS** [comment]
I just checked, nmake does not support executing and capturing commands...

**Comment by niner** [comment]
With commits 62d7a4326978bbfe660b71dba0d32af93bdb2dff d9c56bc53209f9576b5f40213e77b6f142ca4bba 07ad97b138139a00c44c4f179c0eed2b6ed08b3d e7b733251505473b5b7c3aeb2901b14fdf5986e1 fdeea9160ced13259450a813f8c64b5b1bff7e0a and b2dda91a813bcbce34e23434f92126d0efbe24ca it should now be possible to install Inline::Perl5 on Windows. Please try again.

Many thanks to wbiker++ for playing guinea pig and giving feedback :)

**Comment by ryn1x** [comment]
I used zef and this worked for me: https://github.com/niner/Inline-Perl5/issues/105

**Comment by niner** [comment]
I read the last comment as "this is fixed". Closing.
