### ISSUE TITLE
Problem Installing on ubuntu:14.04

### ISSUE THREAD

**Issue by gaorongchao** [niner/Inline-Perl5#50]
panda install Inline::Perl5
==> Fetching Inline::Perl5
==> Building Inline::Perl5
gcc -Wall p5helper.c `perl -MExtUtils::Embed -e ccopts -e ldopts` -shared -o /home/grc/.panda-work/1452095141_1/resources/libraries/libp5helper.so -fPIC -g
/usr/bin/ld: cannot find -lperl
collect2: error: ld returned 1 exit status
make: *** [/home/grc/.panda-work/1452095141_1/resources/libraries/libp5helper.so] 错误 1
The spawned process exited unsuccessfully (exit code: 2)
  in method build at /home/grc/.panda-work/1452095141_1/Build.pm line 22
  in block  at /home/grc/.rakudobrew/moar-nom/install/share/perl6/site/sources/CD95EC778FC8A37BDD0883D5A2F63CE6D7300623 line 12
  in method build at /home/grc/.rakudobrew/moar-nom/install/share/perl6/site/sources/CD95EC778FC8A37BDD0883D5A2F63CE6D7300623 line 8
  in method install at /home/grc/.rakudobrew/moar-nom/install/share/perl6/site/sources/38FD5C879924B42FAD06A34BB816FD9C0DECD91B line 133
  in method resolve at /home/grc/.rakudobrew/moar-nom/install/share/perl6/site/sources/38FD5C879924B42FAD06A34BB816FD9C0DECD91B line 219
  in sub MAIN at /home/grc/.rakudobrew/moar-nom/install/share/perl6/site/resources/506BFEE5608CF7B31E3073D0BDD41C905CB129B8 line 18
  in block <unit> at /home/grc/.rakudobrew/moar-nom/install/share/perl6/site/resources/506BFEE5608CF7B31E3073D0BDD41C905CB129B8 line 150

**Comment by niner** [comment]
Please install the libperl-dev package and try again.

**Comment by draxil** [comment]
Can confirm this works in (roughly) the same ubuntu:
> $ lsb_release -d
> Description:    Ubuntu 14.04.3 LTS

Before: 

>panda install Inline::Perl5
>==> Fetching Inline::Perl5
>==> Building Inline::Perl5
>gcc -Wall p5helper.c `perl -MExtUtils::Embed -e ccopts -e ldopts` -shared -o /home/joe/code/hiveline/.panda-work/1453986346_1/resources/libraries/libp5helper.so -fPIC -g
>/usr/bin/ld: cannot find -lperl
>collect2: error: ld returned 1 exit status
> ...

After:

> sudo apt-get install libperl-dev
> panda install Inline::Perl5
> ==> Fetching Inline::Perl5
> ==> Building Inline::Perl5
> gcc -Wall p5helper.c `perl -MExtUtils::Embed -e ccopts -e ldopts` -shared -o /home/joe/code/hiveline/.panda-work/1453986436_1/resources/libraries/libp5helper.so -fPIC -g
> ==> Testing Inline::Perl5
> ...
> Result: PASS
> ==> Installing Inline::Perl5
> ==> Successfully installed Inline::Perl5

**Comment by niner** [comment]
Thanks for the info!
