### ISSUE TITLE
Problem Installing on Mac OSX 10.10.5 (Yosemite)

### ISSUE THREAD

**Issue by tsalada** [niner/Inline-Perl5#51]
Tests for t/inherit.t and t/perl5parent.t failed:

===SORRY!===
Invalid version format (version required) at /Library/Perl/5.18/Module/Runtime.pm line 386.
BEGIN failed--compilation aborted at t/lib/Foo.pm line 3.
Compilation failed in require at (eval 1) line 78.
BEGIN failed--compilation aborted.

t/inherit.t ...................
Dubious, test returned 255 (wstat 65280, 0xff00)
## Failed 10/10 subtests

Invalid version format (version required) at /Library/Perl/5.18/Module/Runtime.pm line 386.
BEGIN failed--compilation aborted at (eval 174) line 4.

  in method run at /Users/jpolanik/Documents/myPerl6/.panda-work/1453321001_1/lib/Inline/Perl5.pm6 line 430
  in block <unit> at t/perl5parent.t line 17

t/perl5parent.t ...............
Dubious, test returned 255 (wstat 65280, 0xff00)
## Failed 8/8 subtests

I'm using Perl v5.18.2
From perl -V: config_args='-ds -e -Dprefix=/usr -Dccflags=-g  -pipe  -Dldflags= -Dman3ext=3pm -Duseithreads -Duseshrplib -Dinc_version_list=none -Dcc=cc'

**Comment by ssotka** [comment]
I was seeing the same errors on OS X El Capitan.  I installed Moose and Test::More, then retried installing Inline::Perl5 which succeeded.

**Comment by johnsaigle** [comment]
+1 for this issue. macOS Sierra.

**Comment by niner** [comment]
Honestly I don't know what to do about this. I do not have OS X, so I cannot debug anything there. The tests in question do check if Moose is installed and will skip if it isn't, but those errors look like a broken Moose installation. @ssotka's comment supports this hypothesis.

Any suggestions?

**Comment by niner** [comment]
Closing due to lack of feedback and no way for me to debug this.
