### ISSUE TITLE
Use Inline::Perl5 is very slow under Linux

### ISSUE THREAD

**Issue by doughunt** [niner/Inline-Perl5#55]
Currently, 'use Inline::Perl5' is too slow under Linux for use in all but very long-running applications:

`[dhunt@fox src]$ time perl6 -e 'use Inline::Perl5'

real       0m12.651s
user       0m12.398s
sys        0m0.243s
[dhunt@fox src]$ perl6 -v
This is Rakudo version 2016.02-77-g855de77 built on MoarVM version 2016.02-8-ga329e2d
implementing Perl 6.c.
[dhunt@fox src]$ uname -a
Linux fox.cosmic.ucar.edu 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

`
Are there any plans to speed this up?  As a longtime perl5 user with a large production application, this functionality would allow me to start a migration to perl6.

Many thanks, 

  Doug Hunt

**Comment by niner** [comment]
This is now fixed in version 0.6 :)

**Comment by doughunt** [comment]
Hi Niner:  Very cool!  Now

perl6 -e 'use Inline::Perl5'

takes 0.5 seconds on my CentOS 6 box.

Thanks much!

--Doug Hunt
