### ISSUE TITLE
@ARGV does not get set up

### ISSUE THREAD

**Issue by ufobat** [niner/Inline-Perl5#56]
the ARGV array is not getting filled with the values from the. It would be cool if this could be archived so you can for example run MooseX::App things.

martin@thetis ~ % cat MyArgv.pm
package MyArgv;

use strict;
use Data::Dumper;
sub run {
    print Dumper \@ARGV;
};

1;
martin@thetis ~ % cat myargv.p6
#!/usr/bin/env perl6

use MyArgv:from<Perl5>;

MyArgv.run();

**Comment by niner** [comment]
Implemented in commit e4add10e23293f7f8bd6ae6d93bbeab89a67e38a which is included in version 0.7
