### ISSUE TITLE
Importing perl5 function names into perl6 namespace

### ISSUE THREAD

**Issue by sisyphus** [niner/Inline-Perl5#57]
Hi,
In using Inline::Perl5 to access the perl5 extension Math::MPFR from perl6, I find that the following works fine:

use Inline::Perl5;
my $p5 = Inline::Perl5.new;
$p5.use('Math::MPFR');
Math::MPFR::Rmpfr_set_default_prec(113);

The last line simply changes default precision from current value (53) to 113 bits.

Given that the Rmpfr_set_default_prec() function is exported (@EXPORT_OK) by MPFR.pm, is there a way that I can access that function from perl6 without having to specify its fully qualified name ?

That is, is there some construct that would allow me to import that function into the perl6 namespace and rewrite that last line as simply:

Rmpfr_set_default_prec(160);

If not, is it reasonable to request such a capability of perl6 and/or Inline::Perl5 ?

The function can also be imported (in perl5) under the :mpfr tag, and I tried inserting (immediately prior to the last line of code in the above demo):

Math::MPFR::import('Math::MPFR', ':mpfr');

That didn't cause any error but I still had to provide the fully qualified function name. (I presume it successfully imported 'Rmpfr_set_default__prec' into perl5's namespace, but not into perl6's.)

Cheers,
Rob

**Comment by niner** [comment]
This works almost exactly as in Perl 5 itself:

use Math::MPFR:from<Perl5> ":mpfr";
Rmpfr_set_default_prec(160);

Or alternatively:

use Math::MPFR:from<Perl5> "Rmpfr_set_default_prec";
Rmpfr_set_default_prec(160);

No need to even state "use Inline::Perl5;". Rakudo will load it automatically for you. The "use Foo:from<Perl5>" form has the other advantage of running at BEGIN time which means that it actually can export names to your compilation unit. The $p5.use('Math::MPFR') simply runs too late after the compiler has already tried to find the Rmpfr_set_default_prec function and failed.

**Comment by niner** [comment]
Ah, markdown ate the angle brackets, this is the correct code in case you only read the email:
```
use Math::MPFR:from<Perl5> ":mpfr";
Rmpfr_set_default_prec(160);
```
