### ISSUE TITLE
Operator overloading

### ISSUE THREAD

**Issue by sisyphus** [niner/Inline-Perl5#58]
Thank you @niner for your help with Issue #57, and thank you for Inline::Perl5.
I apologise for treating this forum as a perl6 user help list. My intention is that this will be the last time I do that.

From perl6, I can now access the functions in Math::MPFR as easily as I can from perl5.

However, I have not worked out how to access in perl6 the math & comparison operator  overloading such as is available with Math::MPFR objects in perl5.

Does anyone here have any hints to offer about this, or links to relevant documentation ?
I haven't been able to find any documentation at all regarding overloading of perl6 operators.

Cheers,
Rob

**Comment by niner** [comment]
http://doc.perl6.org/language/functions#Defining_Operators

That said, it may be worthwhile digging into supporting more overloaded operators. Currently we only support overloaded stringification of Perl 5 objects.

**Comment by sisyphus** [comment]
Thanks - I'll make a concerted effort to see if I can get my head around that (and other) documentation.

I had guessed that the perl5 overloading of "" was being accessed somehow.
I think the convenience of Inline::Perl5 support for other overloading of Perl 5 objects would be a welcome addition.

In the meantime, the lack of that support is not preventing me from doing anything - it just makes for  occasional extra typing, which is not really such a big deal.

Thanks again !

(I'm not sure whether you want this issue to remain open or not. I'll leave it to you to close it if you so wish.)

Cheers,
Rob

**Comment by niner** [comment]
Inline::Perl5 is supporting overloaded numification since commit d7d908fc
I've now implemented overloading support for generated wrapper classes, too. This should take care of most needs. Closing.
