### ISSUE TITLE
expected 0 or 1 arguments but got 2 in method invoke

### ISSUE THREAD

**Issue by zoffixznet** [niner/Inline-Perl5#60]
This code:

```perl6
use Mojo::DOM:from<Perl5>;
my $dom = Mojo::DOM.new: '<h1>Foo</h1>';
$dom.find("h1").each({ say .<id> });
```
Produces this error:
```
Too many positionals passed; expected 0 or 1 arguments but got 2
  in method invoke at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/2DDC3CA4D43E8307229B622394E5256F089707DD (Inline::Perl5) line 507
  in method invoke at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/2DDC3CA4D43E8307229B622394E5256F089707DD (Inline::Perl5) line 482
  in block  at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/2DDC3CA4D43E8307229B622394E5256F089707DD (Inline::Perl5) line 991
  in block <unit> at to-html.p6 line 3
```

It seems it doesn't matter at all what code is inside the block passed to `.each`. Even if you pass an empty `sub {}` the error appears.

**Comment by zoffixznet** [comment]
Rewrote the code slightly and managed to generate a different error in method `invoke`, if this is helpful:

```perl6
use Mojo::DOM:from<Perl5>;
my $dom = Mojo::DOM.new: '<h1>Foo</h1>';
for $dom.find("h1").each {
}
```
```
Could not find method "map" of "Mojo::DOM" object
  in method invoke at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/2DDC3CA4D43E8307229B622394E5256F089707DD (Inline::Perl5) line 507
  in method invoke at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/2DDC3CA4D43E8307229B622394E5256F089707DD (Inline::Perl5) line 482
  in method <anon> at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/2DDC3CA4D43E8307229B622394E5256F089707DD (Inline::Perl5) line 998
  in block <unit> at to-html.p6 line 3
```

**Comment by niner** [comment]
From the documentation of Mojo::Collection, the .each method is passed two arguments:
```
$collection->each(sub {
  my ($e, $num) = @_;
```

In Perl 6 anonymous blocks have by default one optional argument. If you pass it more than one, you get the error message you posted:

nine@sphinx:~> perl6 -e '{ say $_ }(1, 2)'
Too many positionals passed; expected 0 or 1 arguments but got 2

To get around that, give the block an explicit signature:
`$dom.find("h1").each(-> $e, $num { say $e.<id> });`

The "Could not find method "map" of "Mojo::DOM" object" error is Perl 6' single argument rule at work. In your example .each returns only a single object, so Perl 6 assumes this is a Positional and calls .map on it (for loops are compiled to calls to .map on the list). The error goes away as soon as the .each call returns more than one element:
`perl6 -e 'use Mojo::DOM:from<Perl5>; my $dom = Mojo::DOM.new: "<h1>Foo</h1><h1>Bar</h1>"; for $dom.find("h1").each { }'`

You can get around that by assiging the results of the .each call to an array as you mentioned or by explicitly treating it as a list: `for list $dom.find("h1").each { .all_text.say }`
