### ISSUE TITLE
segfaulting

### ISSUE THREAD

**Issue by jdv** [niner/Inline-Perl5#63]
On fedora 24 beta.
Have the latest rakudo from source (clone,Configure.pl gen-moar, install).  make test passes and otherwise seems ok.
Have perl v5.24.0 via perlbrew (perlbrew install perl-5.24.0 -Duseshrplib)
Get this on all tests tried - https://gist.github.com/anonymous/028fb20bc9dd66fce13a3ffa281809c2.
I could give login creds for that disposable acct on the box if that would help.

**Comment by niner** [comment]
Inline::Perl5 breaks somewhere between Perl v5.23.7 and v.23.8. Bisecting that range now to get the exact commit.

**Comment by niner** [comment]
Fixed in commit 112f4b9727c870a3de7ba0ee0e8cc28aef3d4556

Thanks for the report!
