### ISSUE TITLE
Switches calls Perl 5.

### ISSUE THREAD

**Issue by wambash** [niner/Inline-Perl5#65]
If i load Perl 5 module and use switches then switches are used on Perl 5 command.
So `perl6 -e 'use Data::Dumper:from<Perl5>; '  -h` shows help for Perl 5 (same as perl -h) with segment fault.
Similarly, `perl6 -e 'use Data::Dumper:from<Perl5>; '  -d` runs debugger etc.

**Comment by awwaiid** [comment]
Closeable from #66

**Comment by niner** [comment]
Fixed by commit 9499d690aef44069ac976a5910098d15ffec0b0d

Thanks for the report and the fix :)
