### ISSUE TITLE
Perl 5's $@ contents unavailable

### ISSUE THREAD

**Issue by lucs** [niner/Inline-Perl5#69]
Given for example the Perl 5 code ｢Net::LDAP->new('junk') or die "$@"｣, it appears that the ｢$@｣ contents are not made available to Perl 6.

Some discussion [here](http://irclog.perlgeek.de/perl6/2016-07-15#i_12847186) on IRC, including gfldex's suggestion: "maybe expose it as %*PERL5<$@>, together with all the other globals". (\<lucs> gfldex: Can I quote you on that in the issue I'm preparing? \<gfldex> lucs: you can, as a likely bad idea with unforseeable consequences) :-)

**Comment by niner** [comment]
Implemented in commits 5e3df6656fab3d566b5f1bf5b895aa6e5629b4b9 and de1dfb6dd9996fadadcf6bb3b4c447ec394f7e78

The only issue I can find with this proposal is that there may be multiple Perl 5 interpreters with different globals. But so far I've always tried to make it easy to use one interpreter and possible to use multiple. Therefore we can use %*PERL5<$@> for the implicit default interpreter and $p5.global('$@') for being explicit.
