### ISSUE TITLE
Using same Perl5 lib in a module and a script, that calls the module 

### ISSUE THREAD

**Issue by wambash** [niner/Inline-Perl5#70]
I have module `url`:
>use v6;
>unit module url;
>use URI:from\<Perl5>;
>
>dd URI.new();

and then I call it
>perl6 -I"."  -e 'use url' #Inline::Perl5::Perl5Object...

it is ok, but if i run
>perl6 -I"."  -e 'use URI:from\<Perl5>; use url'

i will get
>===SORRY!=== Error while compiling /tmp/Perl5/url.pm6
>Undeclared name:
>    URI used at line 5

**Comment by niner** [comment]
Fixed in commit bc82e2741cfe4ca674a574548667dad9925494e0

Thanks for the report!

**Comment by wambash** [comment]
The problem stays if i use a Perl 6 module with same name.
>perl6 -I"." -e 'use URI; use url'

Output:
>Inline::Perl5::Perl5Object.new(ptr => NativeCall::Types::Pointer.new(93195128), perl5 => Inline::Perl5.new)
===SORRY!===
P6M Merging GLOBAL symbols failed: duplicate definition of symbol URI

or vice-versa `URI` in a module and `URI:form<Perl5>` in a one-liner.
