### ISSUE TITLE
Can't seem to use sub-modules packaged in the same file

### ISSUE THREAD

**Issue by MasterDuke17** [niner/Inline-Perl5#72]
I'm trying to use Chart::Gnuplot in a Perl 6 program. I can do 'use Chart::Gnuplot:from<Perl5>' and then Chart::Gnuplot.new(<...>) works just fine. However, Chart::Gnuplot::DataSet.new(<...>) doesn't work, it complains "Could not find symbol '&DataSet'", even though the equivalent call in Perl 5 is ok. I tried, 'use Chart::Gnuplot::DataSet:from<Perl5>;', but that just gave "Can't locate Chart/Gnuplot/DataSet.pm in @INC". See http://irclog.perlgeek.de/perl6/2016-08-05#i_12970710 for some more attempted troubleshooting.

**Comment by niner** [comment]
This should now finally be fixed. Thanks for the report!
