### ISSUE TITLE
Segfault in Promise on call to p5 exported function

### ISSUE THREAD

**Issue by Demayl** [niner/Inline-Perl5#76]
```perl6
use Digest::MD5:from<Perl5> <md5_hex>; 
await start { say md5_hex("123") };
```
```
Segmentation fault (core dumped)
```

perl version 5.22.1 x86_64
perl6 version 2016.10-148-g8064ff1 built on MoarVM version 2016.10-37-gf769569

**Comment by Demayl** [comment]
It works without arguments for md5_hex sub. 
Result is exact like perl 5's call without arguments:
d41d8cd98f00b204e9800998ecf8427e

**Comment by niner** [comment]
Hi! I cannot reproduce the bug with current Inline::Perl5. On November 23rd I committed a change that fixes segfaults when an interpreter is used by multiple threads which fits your example.
Can you please try with the latest Inline::Perl5 (0.22)?

**Comment by Demayl** [comment]
Yes, it works! 
Many thanks!
