### ISSUE TITLE
Something doesn't like Business::ISBN

### ISSUE THREAD

**Issue by briandfoy** [niner/Inline-Perl5#80]
When I try to use this with Business::ISBN, I get this odd behavior:

	$ perl6
	To exit type 'exit' or '^D'
	> use Business::ISBN:from<Perl5>;
	(Any)
	> my $isbn = Business::ISBN.new('978-3-16-148410-0' );
	Inline::Perl5::Perl5Object.new(ptr => NativeCall::Types::Pointer.new(140607834140424), perl5 => Inline::Perl5.new)
	> $isbn.as_isbn10
	Inline::Perl5::Perl5Object.new(ptr => NativeCall::Types::Pointer.new(140607836366528), perl5 => Inline::Perl5.new)

The Test::More example from the README works, but not `call`. Business::ISBN does not load correctly apparently. 

	> use Inline::Perl5
	(Any)
	> my $p5 = Inline::Perl5.new;
	Inline::Perl5.new
	> $p5.call('print', 'Hello World');
	Undefined subroutine &main::print called.

	  in method call at /Applications/Rakudo/share/perl6/site/sources/FC133D3E7EC3B0CBE238C296893894C9AB745A05 (Inline::Perl5) line 752
	  in block <unit> at <unknown file> line 1

	> $p5.use('Test::More');
	(subtest eq_array isa_ok todo explain eq_set can_ok cmp_ok note new_ok diag fail is_deeply plan unlike ok eq_hash skip is require_ok like done_testing isnt todo_skip BAIL_OUT pass use_ok)
	>  $p5.call('Test::More::plan', tests => 1);
	1..1
	1
	> $p5.use('Business::ISBN');
	()

**Comment by niner** [comment]
I don't see anything odd with Business::ISBN here?

> perl -MBusiness::ISBN -E 'my $isbn = Business::ISBN->new("978-3-16-148410-0"); say $isbn; say $isbn->as_isbn10; say $isbn->as_isbn10->as_string;'
Business::ISBN13=HASH(0x1dd2f60)
Business::ISBN10=HASH(0x20bfe28)
3-16-148410-X

Same behavior with Perl 6:
> perl6 -e 'use Business::ISBN:from<Perl5>; my $isbn = Business::ISBN.new("978-3-16-148410-0"); say $isbn; say $isbn.as_isbn10; say $isbn.as_isbn10.as_string;'
Inline::Perl5::Perl5Object.new(ptr => NativeCall::Types::Pointer.new(77694648), perl5 => Inline::Perl5.new)
Inline::Perl5::Perl5Object.new(ptr => NativeCall::Types::Pointer.new(65410376), perl5 => Inline::Perl5.new)
3-16-148410-X

The first two tries just return Business::ISBN objects while the as_string correctly retuns the ISBN as a string.

The "Undefined subroutine &main::print" thing is probably more an oddness of Perl 5. Consider this:

nine@sphinx:~> perl -E '&open("foo")'
Undefined subroutine &main::open called at -e line 1.
nine@sphinx:~> perl -E '&CORE::open("foo")'
nine@sphinx:~> perl -E '&print("foo")'
Undefined subroutine &main::print called at -e line 1.
nine@sphinx:~> perl -E '&CORE::print("foo")'
Undefined subroutine &CORE::print called at -e line 1.

So, the open function is actually CORE::open and available under that name while the only way to call print is without the ampersand.

Even stranger is that one can get the reference to &CORE::print:
> perl -E 'say \&CORE::print'
CODE(0x26b5f48)

I would love to know what's so special about print in Perl 5.

**Comment by briandfoy** [comment]
Ah, I was expecting to see something like (Business::ISBN).
