### ISSUE TITLE
p5 call only works when doubly used in both the lexical and dynamic scopes

### ISSUE THREAD

**Issue by jdv** [niner/Inline-Perl5#87]
See https://gist.github.com/anonymous/46bbf63a822192058a9ac9d06d8c4fb5.

**Comment by niner** [comment]
I suspect this is a lexical_module_loading issue. Will dig deeper.

**Comment by niner** [comment]
Just confirmed that the problem has not existed on rakudo 2016.11 which confirms my suspicions.

**Comment by niner** [comment]
This should now be fixed in Inline::Perl5 0.23. Can you confirm?

**Comment by jdv** [comment]
Looks good to me.  Thanks!
