### ISSUE TITLE
using a module :from<Perl5> iterfers with next.

### ISSUE THREAD

**Issue by thundergnat** [niner/Inline-Perl5#92]
When I run the following snippet:

    use Inline::Perl5;
    use Errno:from<Perl5>; # use ANY module from perl5. Errno is core.

    for 1, 2, 3, 4, 5 -> $x {
        next if $x %% 2;
        print $x
    }

I get:
 WARNINGS for /home/steve/p6/next.p6:
Useless use of constant value next in sink context (line 5)
12345

See IRClogs around: https://irclog.perlgeek.de/perl6/2017-03-20#i_14297078

Rakudo 2017.03 on Moarvm 2017.03 
Inline::Perl5 v0.24
Perl5 5.18.2
running on
Linux Mint

It also happens with older Rakudo and newer Perl5
It seems to not happen on OSX

**Comment by niner** [comment]
Fixed by commit 693e5764168c64584cc74a639ead44f7b9205e73
