### ISSUE TITLE
Won't run from cron

### ISSUE THREAD

**Issue by ToddAndMargo** [niner/Inline-Perl5#93]
Fedora Core 25 ,x64

Okay, to add insult to injury. There is a the Perl5 modules that has attachment capability (Email::Simple). I just found out the hard way that if I place the following
use Inline::Perl5;
use Email::Simple:from;

lines in my program, my program will run perfectly from the command line, but when run from /etc/crontab (where it needs to be run), my program will just disappear.

Mind you I actually did not use this code, I had just pre-placed these lines and had forgotten to comment them out until I actually used them. It was a hair puller to figure out. (Commented out, my program runs perfectly from cron.)

-T

**Comment by niner** [comment]
Sorry for the very late reply. I just can't think of anything that could be wrong with Inline::Perl5 that would cause this. It's probably some kind of installation issue like your perlbrew'd perl not available for the user running the cron job or Inline::Perl5 installed in your user's home directory while the cron job runs with a different user.
FWIW we do have cron jobs using Inline::Perl5 just fine.
