### ISSUE TITLE
Can't use the same Inline::Perl5 with perl6 concurrency:

### ISSUE THREAD

**Issue by draxil** [niner/Inline-Perl5#94]
Can't use the same Inline::Perl5 with perl6 concurrency:

```
#!/usr/bin/env perl6

use v6.c;

use Inline::Perl5;

my $p5 = Inline::Perl5.new;
my $fun = {
    for 1..100 {
	$p5.run("print('foo')" );
    }    
};

my $first = start {
    $fun();
};
my $second = start {
    $fun();
};

await($first);
await($second);
```

**Comment by niner** [comment]
That's a fundamental restriction of Perl 5 and was indeed one of the reasons for starting the Perl 6 project in the first place.
What you can do is run multiple, independent Perl 5 interpreters in separate Perl 6 threads. Just make sure that you create those interpreters in the main thread. That's a restriction that will hopefully go away at some point.

```
#!/usr/bin/env perl6

use v6.c;

use Inline::Perl5;

my $fun = sub ($p5) {
    for 1..100 {
        $p5.run("print('foo')" );
    }
};

my $p5_1 = Inline::Perl5.new;
my $first = start {
    $fun($p5_1);
};
my $p5_2 = Inline::Perl5.new;
my $second = start {
    $fun($p5_2);
};

await($first);
await($second);
```
