### ISSUE TITLE
Can't find a way to call splice() an an Inline::Perl5::Array object.

### ISSUE THREAD

**Issue by ajbuch2000** [niner/Inline-Perl5#98]
Perl 6 `splice` doesn't have a signature with `Inline::Perl5::Array`.

`Inline::Perl5.call` doesn't work with first argument `'splice'` ("Undefined subroutine &main::splice called.") or `'CORE::splice'` ("CORE::splice cannot be called directly").

Similarly for shift and unshift, i.e., operations that change the array itself.

I can create a wrapper using `$p5.run` that calls splice on `$_[0]`, then uses `$p5.call` on that wrapper. That works, but doesn't have the same rather awesome seamlessness that the module provides in general.

**Comment by niner** [comment]
Fixed in https://github.com/niner/Inline-Perl5/commit/92fe4b5935ed76e39fdd1654bc2070144dec8dd4
